name: Python Scheduled Job

on:
  schedule:
    # This runs the script every 30 minutes
    - cron: '*/1 * * * *'

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 sendgrid
      
      - name: Run scraping script
        run: |
          python main.py
